// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// InheritedDHCPConfigFilterList FilterList
//
// The inheritance configuration for a field of type list of identifier that represent list of filter attached to _DHCPConfig_.
//
// swagger:model InheritedDHCPConfigFilterList
func schemaInheritedDHCPConfigFilterList() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _override_: Use the value set in the object.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _override_: Use the value set in the object.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The resource identifier.
			"value": {
				Type: schema.TypeList,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Optional:    true,
				Description: "The resource identifier.",
			},
		},
	}
}

func flattenInheritedDHCPConfigFilterList(r *models.InheritedDHCPConfigFilterList) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"action":       r.Action,
			"display_name": r.DisplayName,
			"source":       r.Source,
			"value":        r.Value,
		},
	}
}

func expandInheritedDHCPConfigFilterList(d []interface{}) *models.InheritedDHCPConfigFilterList {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})
	return &models.InheritedDHCPConfigFilterList{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       in["value"].([]string),
	}
}
