// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcInheritedDHCPConfig InheritedDHCPConfig
//
// The inheritance configuration for a field of type _DHCPConfig_.
//
// swagger:model ipamsvcInheritedDHCPConfig
func schemaIpamsvcInheritedDHCPConfig() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance configuration for _allow_unknown_ field from _DHCPConfig_ object.
			"allow_unknown": {
				Type:        schema.TypeList,
				Elem:        schemaInheritanceInheritedBool(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _allow_unknown_ field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for filters field from _DHCPConfig_ object.
			"filters": {
				Type:        schema.TypeList,
				Elem:        schemaInheritedDHCPConfigFilterList(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for filters field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for _ignore_list_ field from _DHCPConfig_ object.
			"ignore_list": {
				Type:        schema.TypeList,
				Elem:        schemaInheritedDHCPConfigIgnoreItemList(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _ignore_list_ field from _DHCPConfig_ object.",
			},

			// The inheritance configuration for _lease_time_ field from _DHCPConfig_ object.
			"lease_time": {
				Type:        schema.TypeList,
				Elem:        schemaInheritanceInheritedUInt32(),
				MaxItems:    1,
				Optional:    true,
				Description: "The inheritance configuration for _lease_time_ field from _DHCPConfig_ object.",
			},
		},
	}
}

func flattenIpamsvcInheritedDHCPConfig(r *models.IpamsvcInheritedDHCPConfig) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"allow_unknown": flattenInheritanceInheritedBool(r.AllowUnknown),
			"filters":       flattenInheritedDHCPConfigFilterList(r.Filters),
			"ignore_list":   flattenInheritedDHCPConfigIgnoreItemList(r.IgnoreList),
			"lease_time":    flattenInheritanceInheritedUInt32(r.LeaseTime),
		},
	}
}

func expandIpamsvcInheritedDHCPConfig(d []interface{}) *models.IpamsvcInheritedDHCPConfig {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})

	return &models.IpamsvcInheritedDHCPConfig{
		AllowUnknown: expandInheritanceInheritedBool(in["allow_unknown"].([]interface{})),
		Filters:      expandInheritedDHCPConfigFilterList(in["filters"].([]interface{})),
		IgnoreList:   expandInheritedDHCPConfigIgnoreItemList(in["ignore_list"].([]interface{})),
		LeaseTime:    expandInheritanceInheritedUInt32(in["lease_time"].([]interface{})),
	}
}
