// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcInheritedAsmEnableBlock InheritedAsmEnableBlock
//
// The inheritance block for ASM fields: _enable_, _enable_notification_, _reenable_date_.
//
// swagger:model ipamsvcInheritedAsmEnableBlock
func schemaIpamsvcInheritedAsmEnableBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _override_: Use the value set in the object.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _override_: Use the value set in the object.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The inherited value.
			// Read Only: true
			"value": {
				Type:        schema.TypeList,
				Elem:        schemaIpamsvcAsmEnableBlock(),
				Computed:    true,
				Description: "The inherited value.",
			},
		},
	}
}

func flattenIpamsvcInheritedAsmEnableBlock(r *models.IpamsvcInheritedAsmEnableBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"action":       r.Action,
			"display_name": r.DisplayName,
			"source":       r.Source,
			"value":        flattenIpamsvcAsmEnableBlock(r.Value),
		},
	}
}

func expandIpamsvcInheritedAsmEnableBlock(ctx context.Context, d []interface{}) (*models.IpamsvcInheritedAsmEnableBlock, error) {
	if len(d) == 0 || d[0] == nil {
		return nil, nil
	}
	in := d[0].(map[string]interface{})

	value, err := expandIpamsvcAsmEnableBlock(ctx, in["value"].([]interface{}))
	if err != nil {
		tflog.Error(ctx, "Failed to parse 'value' field. The underlying expand function returned an error.")
		return nil, err
	}

	return &models.IpamsvcInheritedAsmEnableBlock{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       value,
	}, nil
}
