// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcDDNSHostnameBlock DDNSHostnameBlock
//
// The dynamic DNS Hostname configuration.
//
// swagger:model ipamsvcDDNSHostnameBlock
func schemaIpamsvcDDNSHostnameBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// Indicates if DDNS should generate a hostname when not supplied by the client.
			"ddns_generate_name": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Indicates if DDNS should generate a hostname when not supplied by the client.",
			},

			// The prefix used in the generation of an FQDN.
			"ddns_generated_prefix": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The prefix used in the generation of an FQDN.",
			},
		},
	}
}

func flattenIpamsvcDDNSHostnameBlock(r *models.IpamsvcDDNSHostnameBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"ddns_generate_name":    r.DdnsGenerateName,
			"ddns_generated_prefix": r.DdnsGeneratedPrefix,
		},
	}
}

func expandIpamsvcDDNSHostnameBlock(d []interface{}) *models.IpamsvcDDNSHostnameBlock {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})

	return &models.IpamsvcDDNSHostnameBlock{
		DdnsGenerateName:    in["ddns_generate_name"].(bool),
		DdnsGeneratedPrefix: in["ddns_generated_prefix"].(string),
	}
}
