// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// InheritedDHCPConfigIgnoreItemList IgnoreItemList
//
// The inheritance configuration for a field that contains a list of _IgnoreItem_ objects
//
// swagger:model InheritedDHCPConfigIgnoreItemList
func schemaInheritedDHCPConfigIgnoreItemList() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _override_: Use the value set in the object.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _override_: Use the value set in the object.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The inherited value.
			// Read Only: true
			"value": {
				Type:        schema.TypeList,
				Elem:        schemaIpamsvcIgnoreItem(),
				Computed:    true,
				Description: "The inherited value.",
			},
		},
	}
}

func flattenInheritedDHCPConfigIgnoreItemList(r *models.InheritedDHCPConfigIgnoreItemList) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	values := make([]map[string]interface{}, 0, len(r.Value))
	for _, value := range r.Value {
		values = append(values, flattenIpamsvcIgnoreItem(value))
	}

	return []interface{}{
		map[string]interface{}{
			"action":       r.Action,
			"display_name": r.DisplayName,
			"source":       r.Source,
			"value":        values,
		},
	}
}

func expandInheritedDHCPConfigIgnoreItemList(d []interface{}) *models.InheritedDHCPConfigIgnoreItemList {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})

	values := make([]*models.IpamsvcIgnoreItem, 0)
	for _, value := range in["value"].([]interface{}) {
		values = append(values, expandIpamsvcIgnoreItem(value.(map[string]interface{})))
	}

	return &models.InheritedDHCPConfigIgnoreItemList{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       values,
	}
}
