// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcDDNSUpdateBlock DDNSBlock
//
// The dynamic DNS configurations, ddns_domain and ddns_send_updates.
//
// swagger:model ipamsvcDDNSUpdateBlock
func schemaIpamsvcDDNSUpdateBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The domain name for DDNS.
			"ddns_domain": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The domain name for DDNS.",
			},

			// Determines if DDNS updates are enabled at this level.
			"ddns_send_updates": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "Determines if DDNS updates are enabled at this level.",
			},
		},
	}
}

func flattenIpamsvcDDNSUpdateBlock(r *models.IpamsvcDDNSUpdateBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"ddns_domain":       r.DdnsDomain,
			"ddns_send_updates": r.DdnsSendUpdates,
		},
	}

}

func expandIpamsvcDDNSUpdateBlock(d []interface{}) *models.IpamsvcDDNSUpdateBlock {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})
	return &models.IpamsvcDDNSUpdateBlock{
		DdnsDomain:      in["ddns_domain"].(string),
		DdnsSendUpdates: in["ddns_send_updates"].(bool),
	}
}
