// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// InheritanceInheritedUInt32 InheritedUInt32
//
// The inheritance configuration for a field of type _UInt32_.
//
// swagger:model inheritanceInheritedUInt32
func schemaInheritanceInheritedUInt32() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting for a field.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _override_: Use the value set in the object.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting for a field.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _override_: Use the value set in the object.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The inherited value.
			// Read Only: true
			"value": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: "The inherited value.",
			},
		},
	}
}

func flattenInheritanceInheritedUInt32(r interface{}) []interface{} {
	if r == nil {
		return []interface{}{}
	}
	switch v := r.(type) {
	case *models.InheritanceInheritedUInt32:
		return []interface{}{
			map[string]interface{}{
				"action":       v.Action,
				"display_name": v.DisplayName,
				"source":       v.Source,
				"value":        v.Value,
			},
		}
	case *models.Inheritance2InheritedUInt32:
		return []interface{}{
			map[string]interface{}{
				"action":       v.Action,
				"display_name": v.DisplayName,
				"source":       v.Source,
				"value":        v.Value,
			},
		}
	}
	return nil
}

func expandInheritanceInheritedUInt32(d []interface{}) *models.InheritanceInheritedUInt32 {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})
	return &models.InheritanceInheritedUInt32{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       int64(in["value"].(int)),
	}
}

func expandInheritance2InheritedUInt32(d []interface{}) *models.Inheritance2InheritedUInt32 {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})
	return &models.Inheritance2InheritedUInt32{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       int64(in["value"].(int)),
	}
}
