// Code generated by go-swagger; DO NOT EDIT.

package b1ddi

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamsvcInheritedDDNSUpdateBlock InheritedDDNSUpdateBlock
//
// The inheritance configuration for ddns_domain and ddns_send_updates.
//
// swagger:model ipamsvcInheritedDDNSUpdateBlock
func schemaIpamsvcInheritedDDNSUpdateBlock() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{

			// The inheritance setting.
			//
			// Valid values are:
			// * _inherit_: Use the inherited value.
			// * _override_: Use the value set in the object.
			//
			// Defaults to _inherit_.
			"action": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The inheritance setting.\n\nValid values are:\n* _inherit_: Use the inherited value.\n* _override_: Use the value set in the object.\n\nDefaults to _inherit_.",
			},

			// The human-readable display name for the object referred to by _source_.
			// Read Only: true
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The human-readable display name for the object referred to by _source_.",
			},

			// The resource identifier.
			"source": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "The resource identifier.",
			},

			// The inherited value.
			// Read Only: true
			"value": {
				Type:        schema.TypeList,
				Elem:        schemaIpamsvcDDNSUpdateBlock(),
				Computed:    true,
				Description: "The inherited value.",
			},
		},
	}
}

func flattenIpamsvcInheritedDDNSUpdateBlock(r *models.IpamsvcInheritedDDNSUpdateBlock) []interface{} {
	if r == nil {
		return []interface{}{}
	}

	return []interface{}{
		map[string]interface{}{
			"action":       r.Action,
			"display_name": r.DisplayName,
			"source":       r.Source,
			"value":        flattenIpamsvcDDNSUpdateBlock(r.Value),
		},
	}
}

func expandIpamsvcInheritedDDNSUpdateBlock(d []interface{}) *models.IpamsvcInheritedDDNSUpdateBlock {
	if len(d) == 0 || d[0] == nil {
		return nil
	}
	in := d[0].(map[string]interface{})
	return &models.IpamsvcInheritedDDNSUpdateBlock{
		Action:      in["action"].(string),
		DisplayName: in["display_name"].(string),
		Source:      in["source"].(string),
		Value:       expandIpamsvcDDNSUpdateBlock(in["value"].([]interface{})),
	}
}
